### ISSUE TITLE
Ilcorsaronero-mc not working

### ISSUE THREAD

**Issue by lollo78** [mancuniancol/script.magnetic.ilcorsaronero-mc#1]
Hi, no results found.
The old quasar provider works fine. This magnetic version give me always empty result, also trying to change settings.
The others magnetic scripts work fine (kickass, 1337x...)

**Comment by mancuniancol** [comment]
Could you please share your kodi log in debug mode using pastebin.com or another site?

**Comment by mancuniancol** [comment]
Btw, could you confirm to me if you are using the same filter configuration?

**Comment by mancuniancol** [comment]
I've done several tests and I cannot reproduce your claim. I will wait for your log and confirmation about the filters

**Comment by lollo78** [comment]
Hi, the filters of the script is like the default ones.
I disabled all the other script and activated debug mode. Here the full Kodi.log:
[kodi.zip](https://github.com/mancuniancol/script.magnetic.ilcorsaronero-mc/files/609701/kodi.zip)

Like described above, ilcorsaronero is the only magnetic script that doesn't work for me.
After the content scan appear only the message "no links found".

Ilcorsaronero is the most important script for my point of view, because I'm italian :D 
If you need other info to help debug... I'm here
thx a lot

**Comment by mancuniancol** [comment]
I will check your log tomorrow. If it works with the old code then I can make it to work with the new code. I will keep you informed of my progress.  Btw, if you know another Italian site which is public. Please, let me know. 

And if you can help me with the translation of magnetic to Italian will be great too.

**Comment by lollo78** [comment]
Hi Ok.
The only survived public-tracker made in Italy is IlCorsaroNero. But if you could add a form to support login inside the script, please consider to add TNTvillage forum. It's very great for tv shows.

Ok for the translation. Point me on the language files that require translation.

**Comment by mancuniancol** [comment]
For the translation. I need the msgstr value. The msgid needs to be in English, because it is the reference. 


https://github.com/mancuniancol/script.magnetic.ilcorsaronero-mc/blob/master/resources/language/Italian/strings.po

**Comment by mancuniancol** [comment]
You can use pastebin.com to send me the translation

**Comment by lollo78** [comment]
Ok, I'll send you the pastebin as soon as possibile ;)

**Comment by mancuniancol** [comment]
I've found the problem. I was using torcache to provide the torrent.  But, torcache is down for good.  I've changed the settings to create a magnet instead.  Usually, I wouldn't release a new version because it can be modified from the settings.  But, I don't have the documentation ready for the users to do it.

Then, please, download version 0.7.8.  After that, you need to call the defaults.  I won't work if you don't call them.

Please, let me know if it works in your side.  I will keep this issue open until you confirm to me

**Comment by lollo78** [comment]
Yes, 0.7.8 works fine.
Thank you a lot for the quick fix

**Comment by mancuniancol** [comment]
Hope to have the translation to update that

**Comment by lollo78** [comment]
Of course!
Italian translation in attached:
[ITALIAN_strings.txt](https://github.com/mancuniancol/script.magnetic.ilcorsaronero-mc/files/611351/ITALIAN_strings.txt)

I'm glad to help you

Hope to see a support for http://forum.tntvillage.scambioetico.org/index.php 
;)
Bye

**Comment by mancuniancol** [comment]
Thank you very much. I will check that site.

**Comment by lollo78** [comment]
Thank to you for your hard work

**Comment by lollo78** [comment]
Thx for the 0.8 release ;)

**Comment by mancuniancol** [comment]
You are welcome
