### ISSUE TITLE
Add demonoid support

### ISSUE THREAD

**Issue by lollo78** [mancuniancol/script.magnetic.ilcorsaronero-mc#2]
Hi mancuniancol 
please consider to add a magnetic script for Demonoid. 
The domain is now http://www.dnoid.me

**Comment by mancuniancol** [comment]
It is not the place for request.  But, that site writes a dirty html code.  That is almost impossible to parse information from them.  It is nightmare of code.  I am not sure if it is too stupid who wrote or too smart to avoid any robot to read the information :( Sorry.

**Comment by lollo78** [comment]
Using the new Demonoid domain (link above) with the old quasar mc's provider works great. Maybe you could adapt the old script  😉

**Comment by mancuniancol** [comment]
Hmmm. I will check that this weekend.
