### ISSUE TITLE
Wrong peers seeds counted

### ISSUE THREAD

**Issue by lollo78** [mancuniancol/script.magnetic.ilcorsaronero-mc#3]
Hi, with some videos there isn't correspondence from peers/seeds shown in the query and the same ones during video playing. Some photos to explain better the issue 
![img_20161211_211746_01](https://cloud.githubusercontent.com/assets/6298682/21083139/3275cbea-bfea-11e6-939c-a6a860747442.jpg)
![img_20161211_211840_01](https://cloud.githubusercontent.com/assets/6298682/21083147/64b3ff46-bfea-11e6-845a-22b3f5ffbf9b.jpg)

There's a way to improve this?

**Comment by mancuniancol** [comment]
It is not provider issue.  You are using magnetic + Quasar, then it is Quasar which checks those values.

Please, open a ticket with Quasar github.  I am not involved directly with that project. Then I cannot help you.

I will close this issue,
